
while True:
    print("")
    print("")
    print("--------------------Welcome! Please choose which topic you would like to learn about.--------------------")
    print("")
    print("")
    print("")
    print("Type 1 to learn about Basic Data Types")
    print("")
    print("Type 2 to learn about the Print function")
    print("")
    print("Type 3 to learn about Variables")
    print("")
    print("Type 4 to learn about Python's Math")
    print("")
    print("Type 5 to learn about Lists")
    print("")
    print("Type 6 to learn about the Input function")
    print("")
    print("Type 7 to learn about Loops")
    print("")
    print("Type 8 to learn about Conditions and IF statements")
    print("")
    print("")
    print("Type 9 to exit.")
    print("")
    print("")

    Select = int(input("Type here: "))


    if Select == 1 :
        print("")
        print("")
        print("What are Data Types?")
        print("Data Types are a type of data that is defined by the values it can take/store, the programming language used,\nor the way that the stored data is used by the program.")
        print("")
        print("There are many Data Types, but the most common and important ones to know are:")
        print("-Intigers (Anything Numeric that does not involve decimals)")
        print("-Floats (Anything Numeric including decimals)")
        print("-Strings (Anything Text related, always must have quotaton marks or '' surrounding the text)")
        print("-Booleans (Can only switch between two values, On and Off (True and False, 1 and 0))")
        print("")
        print("Knowing these basic Data Types is critical to being able to read and write programs in any editor and in any language.")
        print("Try testing this out yourself! Go to your chosen Application/Website and try writing the lines of code (LOS) below")
        print("to familiarize yourself with what can be defined as an Int(iger), Float, Str(ing) and Bool(ean).")
        print("")
        print("")
        print("")
        print("x = 10")
        print("print(type(x))")
        print("")
        print("y = 10.15")
        print("print(type(y))")
        print("")
        print("z = 'Lorem Ipsum'")
        print("print(type(z))")
        print("")
        print("r = True")
        print("print(type(r))")
        print("")
        exit = input("Enter anything to exit back to menu   ")

    elif Select == 2 :
        print("")
        print("")
        print("What does the print() function do?")
        print("The print function does what you would expect it to. It (in this case) displays what you have specified you want to print on the terminal below.")
        print("It can print text (as long as you have quotation marks around said text), as well as text stored in variables.")
        print("")
        print("Knowing how to use the print function is crucial to being able to display information as text on the terminal/output device,\nas well as informing and/or instructing the user as shown by this program.")
        print("")
        print("Try testing this out for yourself! Go to your chosen Application/Website and try writing the lines of code (LOS) below")
        print("to familiarize yourself with how the print function works, how it can be used, and it's limitations.")
        print("")
        print("print('Stringing together ethical means of displaying text 123')")
        print("")
        print("")
        print("")
        print("text = 'Testing Text Since 1992'")
        print("print(text)")
        print("")
        exit = input("Enter anything to exit back to menu   ")

    elif Select == 3 :
        print("")
        print("")
        print("What are Variables?")
        print("")
        print("Variables, in most programming languages, are a means of storing data values. Variables are one of the most important functions in any\nprogramming language, as they can store and modify data to you or your program's liking.")
        print("")
        print("Try testing this out for yourself! Go to your chosen Application/Website and try writing the lines of code (LOS) below")
        print("to familiarize yourself variables can be used and modified using code.")
        print("")
        print("")
        print("")
        print("testvariable = 'Twenty Three'")
        print("print(testvariable)")
        print("")
        print("Test_Variable1 = 12")
        print("Test_Variable2 = 24")
        print("print(Test_Variable1 + Test_Variable2)")
        print("print(Test_Variable2 - Test_Variable1)")
        print("")
        print("ReplaceVar = 12")
        print("print(ReplaceVar)")
        print("ReplaceVar = 'Twelve'")
        print("print(ReplaceVar)")
        print("")
        exit = input("Enter anything to exit back to menu   ")

    elif Select == 4 :
        print("")
        print("")
        print("How does math in Python work?")
        print("Math in python works similarly, if not almost identically to how math works in real life.")
        print("")
        print("You have addition (+), subtraction(-), multiplication (*), and division(/).")
        print("")
        print("This time, I wont give you any example code to type. Instead, you yourself must make your own code that utilizes\nall 4 listed mathematical functions.")
        print("If you need any help though, you can always check the second example in the 'variables' section for the addition of two numeric variables.")
        print("")
        exit = input("Enter anything to exit back to menu   ")

    elif Select == 5 :
        print("")
        print("")
        print("What are lists and how can they be used?")
        print("Lists in python are used to store multiple pieces of data (data types, variables, and even other lists) inside of a single variable.")
        print("")
        print("Lists are created when you put a square bracket ([]) after creating an empty variable.\nAn example would be EmptyList = [], which creates and stores an empty list inside of the variable 'EmptyList'")
        print("")
        print("Try testing this out for yourself! Go to your chosen Application/Website and try writing the lines of code (LOS) below")
        print("to try out and familiarize yourself with how you can modify and use lists.")
        print("")
        print("")
        print("List = [1, 2, '3', 'four']")
        print("")
        print("print(List)")
        print("")
        print("List.append(5)")
        print("")
        print("This command adds the selected value to the end of the list")
        print("")
        print("print(List)")
        print("")
        print("List.insert(2, 1.5)")
        print("")
        print("This command inserts the selected value (1.5) into the selected index (2)")
        print("")
        print("print(List)")
        print("")
        print("List.remove('four')")
        print("")
        print("This command removes a specific value in the list. In this case, it will remove the value 'four' from the list.")
        print("")
        print("print(List)")
        print("")
        exit = input("Enter anything to exit back to menu   ")

    elif Select == 6 :
        print("")
        print("")
        print("What does the input function do and how can it be used?")
        print("The input function allows for user input by creating a text box that can be typed into.")
        print("The input must be stored in a variable, and it can also be specified as to what type of input the user is allowed to type.")
        print("You can also add text inside of the input function to instruct the user as well.")
        print("")
        print("Try testing this out for yourself! Go to your chosen Application/Website and try writing the lines of code (LOS) below")
        print("to try out and familiarize yourself with how you can modify and use the input function.")
        print("")
        print("allintput = input('This input can store all types of inputs:   ')")
        print("print(allinput)")
        print("")
        print("intinput = int(input('This input can only store numbers, but cannot store text or decimals:   ))")
        print("print(intinput)")
        print("")
        print("strinput = str(input('This input can only store text, but cannot store numbers or decimals:   ))")
        print("print(strinput)")
        print("")
        print("floatinput = float(input('This input can store decimals and numbers (automatically adds .0), but cannot store text:   ))")
        print("print(floatinput)")
        print("")
        exit = input("Enter anything to exit back to menu   ")
        
    elif Select == 7 :
        print("")
        print("")
        print("What are loops and how do you use them?")
        print("Loops, as the name suggests, allow for the repitition of something over and over again until a particular conditions is satisfied.")
        print("The most common loop is the 'for i in range(x):' loop.")
        print("This loop uses an intiger as the x value, and loops from 0 to x-1.")
        print("")
        print("Try testing this out for yourself! Go to your chosen Application/Website and try writing the lines of code (LOS) below")
        print("to try out and familiarize yourself with how you can use loops.")
        print("")
        print("x = 20")
        print("for i in range(x):")
        print("     print('looping 20 times')")
        print("")
        print("You dont have to use a variable, you can just type the number in as well.")
        print("")
        print("for i in range(20):")
        print("     print('looping 20 times')")
        print("")
        print("You can also use the 'Break' function to prematurely close a loop.")
        print("")
        print("")
        print("")
        print("")
        print("You can also make an 'else' statemet so that once the loop ends, something ELSE happends. Get it?")
        print("")
        print("j = 10")
        print("for i in range(j):")
        print("     print('looping 10 times')")
        print("else:")
        print("     print('Finished Looping')")
        print("")
        exit = input("Enter anything to exit back to menu   ")
        
    elif Select == 8 :
        print("")
        print("")
        print("What are conditions and IF statements and how do you use them?")
        print("")
        print("Conditions:")
        print("Python supports the usual logical conditions from maths:")
        print("Equals: a == b")
        print("Not Equals: a != b")
        print("Less Than: a < b")
        print("Less Than or Equal To: a <= b")
        print("Greater Than: a > b")
        print("Greater Than or Equal To: a >= b")
        print("")
        print("These conditions are used in many ways, but are used most commonly in 'if statements' and loops.")
        print("")
        print("If statements:")
        print("")
        print("'If statements' are written as follows:\n\nif a <insert condition> b:\n   <insert code here>")
        print("")
        print("")
        print("Using the example above, go to your chosen Application/Website and try experimenting with 'if statements' and conditions.\nYou can also use the code in this program to assist you if you get confused.")
        print("")
        exit = input("Enter anything to exit back to menu   ")

    elif Select == 9 :
        break

